rly_file = "Metra_Electric.rly"
ttb_files = [ "Weekday_2020_MetraElectric_5am.ttb",]
ssn_files = [ "Metra_Electric_Weekday_2020_MetraElectric_5am.ssn",]
img_files = [ "Metra_Electric.bmp",]
doc_files = [ "README.md",]
release_date = "2022-02-23"
version = "2.0.0"
country_code = "US"
factual = true
description = "A representation of the northern part of the Metra Electric District network run by the Metra commuter rail system in Chicago, US"
display_name = "Metra Electric District Chicago"
name = "Metra Electric District"
author = "Krizar"
contributors = []
year = 2023
signal_position = "left"
